import Foundation

enum DailyMemoryExportKind: String, Codable, CaseIterable, Sendable {
    case markdown
    case obsidian
    case logseq
}

struct DailyMemoryExportConfiguration: Equatable {
    var destinationDirectory: URL
    var format: DailyMemoryExportKind
}

enum DailyMemoryExportPass: Equatable, Sendable {
    /// Writes or refreshes the day's note.
    case refresh
    /// A past day the export missed, because the Mac was asleep or off at
    /// the export hour. Written only if the folder has no file for that day
    /// and something was recorded.
    case catchUp
}

enum DailyMemoryExportError: LocalizedError, Equatable {
    case destinationCollision(URL)
    case generatedFileModified(URL)

    var errorDescription: String? {
        switch self {
        case .destinationCollision(let url):
            "Daily memory export stopped because \(url.lastPathComponent) already exists "
                + "and was not generated by LokalBot. Choose another folder or move that file."
        case .generatedFileModified(let url):
            "Daily memory export stopped because \(url.lastPathComponent) was edited after "
                + "LokalBot generated it. Your edits were preserved; move the file or choose "
                + "another export folder to resume automatic refreshes."
        }
    }
}

struct DailyMemoryMeetingReference: Equatable {
    var id: String
    var title: String
    var startedAt: Date
    var durationSeconds: TimeInterval
}

struct DailyMemoryExportSnapshot: Equatable {
    var day: Date
    var digest: String?
    /// A digest exists but no longer matches the day's evidence, so it is
    /// left out until the digest is updated.
    var digestIsOutOfDate = false
    var meetings: [DailyMemoryMeetingReference]
    var savedMoments: [ScreenMemorySavedMoment]
    var stats: ScreenMemoryDaySummary
    var appUsage: [ScreenMemoryAppUsage]

    var isEmpty: Bool {
        digest == nil && meetings.isEmpty && savedMoments.isEmpty && appUsage.isEmpty
            && stats.trackedSeconds == 0 && stats.screenshotCount == 0
    }
}

/// Injection seam keeps rendering and atomic file behavior testable without a
/// live meeting library or SQLite database.
protocol DailyMemoryExportSource {
    func snapshot(for day: Date, interval: DateInterval) throws -> DailyMemoryExportSnapshot
}

/// Default source for the scheduler: existing journal Markdown plus read-only
/// meeting and screen-memory queries. Screen data is optional when day tracking
/// has never created a database; an existing-but-unreadable database still
/// fails loudly instead of silently publishing incomplete data.
struct FileDailyMemoryExportSource: DailyMemoryExportSource {
    var root: URL
    var evidenceSource: FileDailyEvidenceSource
    var calendar: Calendar

    init(
        root: URL = SessionLookup.storageRootURL,
        screenReader: (any ScreenMemoryReading)? = nil,
        calendar: Calendar = .current
    ) {
        self.root = root
        evidenceSource = FileDailyEvidenceSource(
            root: root,
            screenReader: screenReader,
            calendar: calendar)
        self.calendar = calendar
    }

    func snapshot(for day: Date, interval _: DateInterval) throws -> DailyMemoryExportSnapshot {
        let allMeetings = try SessionLookup.loadAllMeetings(root: root)
        let evidence = try evidenceSource.snapshot(
            for: day,
            meetings: allMeetings,
            includeDetailedActivity: false)
        let digest = DailyEvidenceArtifacts.generatedDigest(
            for: evidence,
            root: root,
            calendar: calendar)
        let meetings = evidence.meetings.map {
            DailyMemoryMeetingReference(
                id: SessionLookup.shortID($0.meeting.id),
                title: $0.meeting.title,
                startedAt: $0.meeting.startedAt,
                durationSeconds: $0.meeting.duration ?? 0)
        }

        return DailyMemoryExportSnapshot(
            day: evidence.day,
            digest: digest?.isCurrent == true ? digest?.text : nil,
            digestIsOutOfDate: digest?.isCurrent == false,
            meetings: meetings,
            savedMoments: evidence.savedMoments,
            stats: evidence.stats,
            appUsage: evidence.appUsage)
    }
}

struct DailyMemoryExportService {
    static let generatedFileMarker = "<!-- Generated by LokalBot daily memory export. -->"
    static let ownershipSidecarSuffix = GeneratedFileWriter.sidecarSuffix

    enum Outcome: Equatable {
        case written(URL)
        case unchanged(URL)
        /// A catch-up found a file already there, or nothing recorded.
        case skipped
    }

    var source: any DailyMemoryExportSource
    var calendar: Calendar
    var fileManager: FileManager

    init(
        source: any DailyMemoryExportSource,
        calendar: Calendar = .current,
        fileManager: FileManager = .default
    ) {
        self.source = source
        self.calendar = calendar
        self.fileManager = fileManager
    }

    /// Rewrites one deterministic day file. A hidden sidecar records the hash
    /// of the exact bytes last emitted by LokalBot. Refresh is allowed only if
    /// the current file still matches that hash, so a user edit made after
    /// generation is never overwritten. Identical content keeps its mtime;
    /// changed app-owned content uses same-directory atomic replacement.
    func export(day: Date, configuration: DailyMemoryExportConfiguration,
                pass: DailyMemoryExportPass = .refresh) throws -> Outcome {
        let start = calendar.startOfDay(for: day)
        let end = calendar.date(byAdding: .day, value: 1, to: start)
            ?? start.addingTimeInterval(86_400)
        let outputURL = configuration.destinationDirectory.appendingPathComponent(
            fileName(for: start, format: configuration.format),
            isDirectory: false)
        if pass == .catchUp, fileManager.fileExists(atPath: outputURL.path) { return .skipped }
        let snapshot = try source.snapshot(
            for: start,
            interval: DateInterval(start: start, end: end))
        if pass == .catchUp, snapshot.isEmpty { return .skipped }
        let text = render(snapshot, format: configuration.format)
        let data = Data(text.utf8)
        try Task.checkCancellation()
        try fileManager.createDirectory(
            at: configuration.destinationDirectory,
            withIntermediateDirectories: true)
        do {
            let changed = try GeneratedFileWriter.write(data, to: outputURL, marker: Self.generatedFileMarker)
            return changed ? .written(outputURL) : .unchanged(outputURL)
        } catch GeneratedFileWriter.WriteError.collision {
            throw DailyMemoryExportError.destinationCollision(outputURL)
        } catch is GeneratedFileWriter.WriteError {
            throw DailyMemoryExportError.generatedFileModified(outputURL)
        }
    }

    static func ownershipSidecarURL(for outputURL: URL) -> URL {
        GeneratedFileWriter.sidecarURL(for: outputURL)
    }

    func render(_ snapshot: DailyMemoryExportSnapshot, format: DailyMemoryExportKind) -> String {
        var sections: [String] = []
        let key = dayKey(snapshot.day, separator: "-")
        switch format {
        case .markdown:
            sections.append("""
                \(Self.generatedFileMarker)

                # Daily memory — \(displayDate(snapshot.day))
                """)
        case .obsidian:
            sections.append("""
                ---
                date: \(key)
                tags:
                  - lokalbot/daily-memory
                source: LokalBot
                ---

                \(Self.generatedFileMarker)

                # Daily memory — \(displayDate(snapshot.day))
                """)
        case .logseq:
            sections.append("""
                title:: Daily memory — \(displayDate(snapshot.day))
                date:: \(key)
                tags:: lokalbot, daily-memory

                \(Self.generatedFileMarker)

                # Daily memory — \(displayDate(snapshot.day))
                """)
        }

        let digest = snapshot.digest?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let missingDigest = snapshot.digestIsOutOfDate
            ? "_The day's digest is out of date. It is added here once it is updated._"
            : "_No day digest was generated._"
        sections.append("## Digest\n\n" + ((digest?.isEmpty == false) ? digest! : missingDigest))
        sections.append(meetingsSection(snapshot.meetings))
        sections.append(savedMomentsSection(snapshot.savedMoments))
        sections.append(statsSection(snapshot))
        return sections.joined(separator: "\n\n") + "\n"
    }

    private func meetingsSection(_ meetings: [DailyMemoryMeetingReference]) -> String {
        guard !meetings.isEmpty else { return "## Meetings\n\n_No meetings._" }
        let rows = meetings.map { meeting in
            "- **\(time(meeting.startedAt))** — \(inline(meeting.title)) · "
                + "\(duration(meeting.durationSeconds)) (`\(meeting.id)`)"
        }
        return "## Meetings\n\n" + rows.joined(separator: "\n")
    }

    private func savedMomentsSection(_ moments: [ScreenMemorySavedMoment]) -> String {
        guard !moments.isEmpty else { return "## Saved moments\n\n_No saved moments._" }
        let rows = moments.map { moment -> String in
            let title = moment.windowTitle.isEmpty
                ? inline(moment.app)
                : "\(inline(moment.app)) — \(inline(moment.windowTitle))"
            var lines = [
                "- **\(time(moment.capturedAt))** — \(title) (`screen:\(moment.snapshotID)`)",
            ]
            let note = singleLine(moment.note)
            if !note.isEmpty { lines.append("  - Note: \(inline(note))") }
            let excerpt = singleLine(moment.ocrExcerpt)
            if !excerpt.isEmpty { lines.append("  - OCR: \(inline(excerpt))") }
            return lines.joined(separator: "\n")
        }
        return "## Saved moments\n\n" + rows.joined(separator: "\n")
    }

    private func statsSection(_ snapshot: DailyMemoryExportSnapshot) -> String {
        let stats = snapshot.stats
        var lines = [
            "## Day stats",
            "",
            "| Metric | Value |",
            "| --- | ---: |",
            "| Tracked time | \(duration(stats.trackedSeconds)) |",
            "| Apps | \(stats.appCount) |",
            "| Activity blocks | \(stats.activityBlockCount) |",
            "| Screenshots | \(stats.screenshotCount) |",
            "| Saved moments | \(stats.savedMomentCount) |",
            "| Meetings | \(snapshot.meetings.count) |",
        ]
        if !snapshot.appUsage.isEmpty {
            lines.append(contentsOf: ["", "### App usage", ""])
            lines += snapshot.appUsage.map {
                "- \(inline($0.app)): \(duration($0.durationSeconds))"
            }
        }
        return lines.joined(separator: "\n")
    }

    private func fileName(for day: Date, format: DailyMemoryExportKind) -> String {
        let separator: Character = format == .logseq ? "_" : "-"
        return dayKey(day, separator: separator) + ".md"
    }

    private func dayKey(_ date: Date, separator: Character) -> String {
        let components = calendar.dateComponents([.year, .month, .day], from: date)
        return String(
            format: "%04d\(separator)%02d\(separator)%02d",
            components.year ?? 0, components.month ?? 0, components.day ?? 0)
    }

    private func displayDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "MMMM d, yyyy"
        return formatter.string(from: date)
    }

    private func time(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "HH:mm"
        return formatter.string(from: date)
    }

    private func duration(_ seconds: TimeInterval) -> String {
        let minutes = max(0, Int(seconds.rounded()) / 60)
        if minutes >= 60 { return "\(minutes / 60)h \(minutes % 60)m" }
        return "\(minutes)m"
    }

    private func singleLine(_ value: String) -> String {
        value.split(whereSeparator: \Character.isWhitespace)
            .joined(separator: " ")
    }

    private func inline(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "`", with: "\\`")
            .replacingOccurrences(of: "*", with: "\\*")
            .replacingOccurrences(of: "_", with: "\\_")
            .replacingOccurrences(of: "[", with: "\\[")
            .replacingOccurrences(of: "]", with: "\\]")
            .replacingOccurrences(of: "|", with: "\\|")
    }
}
